### ISSUE TITLE
User gps location 

### ISSUE THREAD

**Issue by MartCube** [xon52/x5-gmaps#1]
Can you provide us a small demo code where we can use this plugin so we can display user's current location.

**Comment by xon52** [comment]
Thanks for trying it out. I made you an example on the demo:
[https://xon52.github.io/x5-gmaps/#setcenterofmaptocurrentlocation](https://xon52.github.io/x5-gmaps/#setcenterofmaptocurrentlocation)
And here's the file for that component:
[https://github.com/xon52/x5-gmaps/blob/master/example/ExampleSetPosition.vue](https://github.com/xon52/x5-gmaps/blob/master/example/ExampleSetPosition.vue)

In short, if you update the map options property it will update the map - so get your new location via the [HTML5 Geolocation API](https://www.w3schools.com/html/html5_geolocation.asp), convert to an object in the form: `{lat, lng}`, and then update your map options property.
