### ISSUE TITLE
Detect marker dragend

### ISSUE THREAD

**Issue by huyhoang160593** [xon52/x5-gmaps#104]
Hello, 
There is anyway I can detect the drag-end event in gmap-maker, the move event is good but it's too sensitive, I only need the lat lng when the drag is stop and that all

**Comment by xon52** [comment]
I have just release v0.6.2 and added `drag`, `dragstart`, and `dragend` events to the marker.
I can't get it to work in the online demo though but seems to be working on other environments. Can you please test it for me?

**Comment by huyhoang160593** [comment]
yeah the event is working fine now, thanks @xon52 <3
