### ISSUE TITLE
Getting Cannot read properties of undefined (reading 'toSpan') error

### ISSUE THREAD

**Issue by kossa** [xon52/x5-gmaps#107]
Hello,

I'm using x5-gmaps version 0.6.2 gmaps-cluster component, sometimes I get this error 
![image](https://user-images.githubusercontent.com/1175584/197846314-dec0e73d-f8d5-491b-93fd-6dc783a87e56.png)

![image](https://user-images.githubusercontent.com/1175584/197846340-1149b7f0-5c2c-467b-ba01-acd4c75ce2a5.png)

**Comment by xon52** [comment]
Thanks @kossa. Have you noticed a consistent way to produce this error?

**Comment by kossa** [comment]
Really I did not understand, getting up this morning it works fine 😅

**Comment by xon52** [comment]
@kossa I have seen this before and I can probably put a guard here to not run the extendBounds() if there is no bounds provided; but I'd like to know what to test. Let me know if you find it again 👍

**Comment by kossa** [comment]
I think yesterday my internet was unstable/slow, I just tried with Fast 3G throttling I got the same error

![image](https://user-images.githubusercontent.com/1175584/197946970-540e8319-48ed-4bba-8f88-6f15709a5c2c.png)

**Comment by xon52** [comment]
I replicated this once, but could not get it again. I have a fix, but will release with the next version. If it is blocking you though let me know and I can release this minor patch.

**Comment by kossa** [comment]
To be honest I'm blocked right now, still cannot continue working, if you can release this patch I'll be very grateful 😇

**Comment by xon52** [comment]
OK, new version released. I think it should fix that. Make a new issue if not, and try and get a way to reproduce it please.

**Comment by kossa** [comment]
Currently it works perfectly, Thank you
