### ISSUE TITLE
Loading Google Maps JavaScript API needs a callback

### ISSUE THREAD

**Issue by kupoback** [xon52/x5-gmaps#110]
Is there a way to pass a parameter for the URL generated for Google Maps to include a callback method? I am getting this in console not:

`Loading the Google Maps JavaScript API without a callback is not supported: https://developers.google.com/maps/documentation/javascript/url-params#required_parameters`

**Comment by xon52** [comment]
Hey mate, are you just trying to fix the error or do you need an additional callback appended to the url?

If it's to fix the error, I cannot replicate it and it appears that it may be an issue with your API key you have provided:

> Your Google Maps may not be functioning for a number of reasons, but the most frequent one is that your Google Map API key may not be set or is set wrongly. You must register your app project on the Google Cloud Platform Console in order to access the Google Maps JavaScript API. Once you have your Google API key, you can add it to your app.
> 
> Both errors and warnings are returned by the Maps JavaScript API. An error means that there was a serious problem loading the Maps JavaScript API. The API won't function on your page since it can't load correctly. An additional notification regarding the loading of the Maps JavaScript API is known as a caution. The warning identifies probable problems in your code that load the Maps JavaScript API or explains the causes of an error. The API will function properly on that page if you just get warnings and no errors. However, we advise you to address these potential problems as well.

[Source](https://www.fresherslive.com/latest/articles/loading-the-google-maps-javascript-api-without-a-callback-is-not-supported-10002171#:~:text=in%20May%202017.-,Loading%20The%20Google%20Maps%20Javascript%20API%20Without%20A%20Callback%20Is%20Not%20Supported,-Your%20Google%20Maps)

Make sure you have included your Google Key as described in [the docs](https://xon52.github.io/x5-gmaps/install.html#npm), and that your Google Key is authorised for the IP address you're calling it from. This is what my key page looks like in the [Credentials page](https://console.cloud.google.com/apis/credentials).
![image](https://user-images.githubusercontent.com/30713944/215903348-fe94544e-cb6c-46cd-8fd7-80fd4cb5017c.png)

**Comment by kupoback** [comment]
Hi there, since I'm using your tool, I would hope you understand that I am familiar with Google API integrations and setup.

Yes, I have a Google Key with the set appropriate APIs enabled, and the IPs setup, however those are all 100% completely irrelevant to my statement.

If you look here [at Googles URL Docs](https://developers.google.com/maps/documentation/javascript/url-params#required_parameters), you'll see there are 2 required parameters, one for the API key, and one for the callback.

In my initial issue message, the console message was in reference to the second required parameter, the function callback. 

If you inspect [this page](https://developers.google.com/maps/documentation/javascript/adding-a-google-map), you'll see generally in the URL, you'll have `?key=XYZ&callback=initMap` where the `initMap` can be whatever method instantiates your Google Map. I'm asking if there is a way with your plugin to provide this callback function.

**Comment by xon52** [comment]
~~Ah ok. So you'd like your own callback to be run alongside `initMap`?~~

~~It's not in there now but shouldn't be too hard to add in. I'll try find some time to explore that.~~

~~I've not seen this callback console warning before so I'm guessing something changed in their API. Are you able to replicate it somewhere I can test myself?~~

Gotcha, I can replicate the error. I'll have a look 👍

**Comment by kupoback** [comment]
Yeah, I'm just looking for a way to pass in a callback function name to it.

A nice to have, would be able to pass in other parameters, like `language`, so that the maps language can be changed if using a site that it utilizing localization

**Comment by xon52** [comment]
Updated the way the config is loaded to the way I do in the Vue 3 version and updated the plugin to v0.7.0. I've added a callback property in the options that can be used.

Check out [Configuration](https://xon52.github.io/x5-gmaps/configuration.html) and let me know if it makes sense (and meets your need). Thanks for the suggestion.

**Comment by kupoback** [comment]
> 

Ayyy, this is perfect! This did the trick for me. Thank you!

Issue fixed with latest release https://github.com/xon52/x5-gmaps/releases/tag/v0.7
