### ISSUE TITLE
Module parse failed: Unexpected token (24:32)

### ISSUE THREAD

**Issue by walnut-co** [xon52/x5-gmaps#112]
installed version "x5-gmaps": "0.7.0"

any suggestions ?

![image](https://user-images.githubusercontent.com/13636878/231348486-29477f02-ddcb-418f-8ccf-40ab17a23e1a.png)

**Comment by xon52** [comment]
@kberawala your error looks to be pointing to the optional chaining used  (`?.`) but I don't know why you would have that error. Only thing I can think of is an old node version?

Regardless, I have released v0.7.1 and removed optional chaining just in case. Not really important, it's just cleaner code.

Try that and let me know.

**Comment by Simbiryan** [comment]
I am using x5-gmaps version 0.7.2 (vuestorefront for magento 2, node v16.15.0) and got the same error

**Comment by xon52** [comment]
Hey @Simbiryan, you are having the same error on the same line?
Can you try v0.7.3 which I just released?
Any chance you can try node v18 (just to test)?

I cannot replicate this and so can't really debug it.

**Comment by sbstnplcn** [comment]
hi, I have the same error using v0.7.4, node 20.10.0 and nuxt 2.17.1
Any idea how to resolve this issue ?

```
 ERROR  Failed to compile with 1 errors

 ERROR  in ./node_modules/x5-gmaps/dist/x5-gmaps.esm.js

Module parse failed: Unexpected token (25:32) 
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   // Remove any existing Google Maps script
|   const oldAPI = document.getElementById(scriptID);
>   if (oldAPI) oldAPI.parentNode?.removeChild(oldAPI);
|   // Get callback reference ready
|   window._gmapsInit = () => resolve();

 @ ./plugins/gmaps.js 1:0-31 3:8-15
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

**Comment by xon52** [comment]
Apologies for the slow reply. Can you edit the actual file in the npm folder to replace the optional chaining with the old way?

```js
if (oldAPI && oldAPI.parentNode) oldAPI.parentNode.removeChild(oldAPI);
```

I can't replicate so can't see if this is the problem?

**Comment by xon52** [comment]
Actually, I found the error on codesandbox, made an update (v0.7.6) and seems to work now. Try that if you're still wanting to use this!
