### ISSUE TITLE
Change pin colors

### ISSUE THREAD

**Issue by kossa** [xon52/x5-gmaps#117]
Hello,

I want to change the pin color like the doc here: https://developers.google.com/maps/documentation/javascript/advanced-markers/basic-customization#scale_the_marker

My question is how to import "PinElement"?

**Comment by xon52** [comment]
Hmm, interesting. That must be something new they introduced. I will see if I can find time to support that. But right now it's not supported.

**Comment by kossa** [comment]
Ok btw I'll use icon url 😁

**Comment by xon52** [comment]
I don't think I will get to this. I suggest upgrading to Vue 3 😅
