### ISSUE TITLE
As of February 21st, 2024, google.maps.Marker is deprecated

### ISSUE THREAD

**Issue by sylvia-ivy** [xon52/x5-gmaps#123]
As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement instead. Please see https://developers.google.com/maps/deprecations for deprecation details.

**Comment by xon52** [comment]
Thanks. As Vue 2 is already EOL, I will let this go down with the ship. Thanks for letting me know!
