### ISSUE TITLE
x5-gmaps not show in laravel app

### ISSUE THREAD

**Issue by tingan** [xon52/x5-gmaps#13]
hi,
i install this npm package and import it in vue component. no error, but the maps doesn't show up, it's blank page for map area. do i need to include maps.js from google to laravel head script or other reasons? thanks.

**Comment by xon52** [comment]
Hi @tingan, unfortunately I don't use Laravel so I'm not sure what the issue is here.

Firstly, just to confirm, you have added the `Vue.use` bit of code in your `main.js`?

```js
import x5GMaps from 'x5-gmaps'
Vue.use(x5GMaps, 'YOUR_GOOGLE_KEY')

new Vue({
  el: '#app',
  render: (h) => h(App),
})
```

Secondly, is there any error or output in the console?

What this does is adds the Google script `https://maps.googleapis.com/maps/api/js` with all the settings and your key into your `<head>`. Theoretically, for Vue to run that code to add the script, your `<head>` shouldn't be overwritten, so I don't think it's that.

Could you try and recreate it using [codesandbox.io](https://codesandbox.io/s/vue) and adding the `x5-gmaps` package along with Laravel? I am happy to investigate the problem if I can replicate it.

**Comment by tingan** [comment]
in app.js
mport x5GMaps from 'x5-gmaps'
// Option 1: Just your key
Vue.use(x5GMaps, 'AIzxxx')

in vue component
 <GmapMarker ref="myMarker"
                            :position="google && new google.maps.LatLng(1.38, 103.8)" />
import { gmapsMap, gmapsMarker } from 'x5-gmaps'

no error in console, i can inspect the map by chrome, the map html code is there, but area is just blank.

**Comment by thebrownfox** [comment]
@tingan you have to give it a height (percentage works as well if it's wrapped correctly)

**Comment by tingan** [comment]
hi, @thefoxie , thx, you are right, it's related with the height of the map, as i copy the code
<template>
  <gmaps-map>
    <gmaps-marker :position="{ lat: -27, lng: 153 }" />
  </gmaps-map>
</template>
and i assume it will works out of box, i inspect the code with chrome, although the height of gmap is 100%, but it didn't show up, but after i change the height to fixed number like 500px, the map show up!
I guess it's related the the parent container of map. the example code should contain the width, height props.
by the way, from the demo, i didn't find the marker cluster functions, does the x5-maps has this function?

**Comment by xon52** [comment]
@tingan yes, if you give it 100% it will be 100% of the parent. If there parent has no height set, 100% of auto is auto, and auto is 0 for the map. Something else you can play around with is VH - I often use 90VH which is 90% of the screen height.

Unfortunately, no, I haven't implemented marker cluster functions. For now, only heatmap is available, but that is something I do want. Please add it as a feature request in a new issue so I don't forget.

**Comment by kossa** [comment]
I had the same issue in Laravel, so I fixed height it works fine :

```
<template>
    <div style="height: 70vh">
        <gmaps-map>
            <gmaps-marker :position="{ lat: -27, lng: 153 }" />
        </gmaps-map>
    </div>
</template>
```

![image](https://user-images.githubusercontent.com/1175584/99783248-778ff800-2b1a-11eb-97e9-54b124c164c1.png)

**Comment by thebrownfox** [comment]
@kossa you don't have to give it viewport height. Works with percents as well. It can work dynamically, ie. you wrap it around flex containers then it takes 100% of what is left.
