### ISSUE TITLE
[Feature Request] Provide map instance to parent

### ISSUE THREAD

**Issue by thebrownfox** [xon52/x5-gmaps#14]
Sometimes it might be useful to access the map instance itself as you do in your children through provide/inject. Right now, I created workaround - custom component that is child of map instance which emits the injected `this.getMap()` to the parent. 

hidden.vue
```vue
<template>
    <div style="display: none"></div>
</template>

<script>
export default {
    name: "Hidden",
    inject: ["getMap", "handleError"],
    emits: ["mounted"],
    mounted() {
        const map = this.getMap();
        this.$emit("mounted", map);
    },
};
</script>
```
parent.vue
```vue
<template>
    <gmaps-map>
        <maps-hidden @mounted="mapInstance = $event" />
    </gmaps-map>
</template>

<script>
export default {
    data() {
        return {
            mapInstance: null,
        };
    }
}      
</script>
```

**Comment by xon52** [comment]
Hmm interesting idea. It may be easier for me to add that emit to the map component itself.
I'll have a think if there's another way before I make the change though.

Might also be worth adding it as a slot prop which would be another way to access it from inside the template.

**Comment by thebrownfox** [comment]
@xon52 that's what I was trying to suggest. This is just a workaround. It should be emitted from the map component itself.

**Comment by xon52** [comment]
Should be done in latest version (0.3.26) @thefoxie, please let me know if it's not working or could be better.
`<gmaps-map />` should have an `@mounted` event that supplies the instance.

**Comment by thebrownfox** [comment]
@xon52 yeah sure works well. Thank you :)

**Comment by thebrownfox** [comment]
There are few other things that might be useful as well, like animated panTo and fitBounds on map items (polygons, circles,...) upon their creation/mount. I have those implemented outside of gmaps components, but it could be useful to others to just toggle the functionality on via prop. If If I find some time over weekend, I will make an issue and commit as well.

**Comment by thebrownfox** [comment]
@xon52 could you pls create pull requests and merge them so we can track those commits in the issues easily? I just found out you switched from camelCase to kebab-case in emitted events which I endorse, but it's breaking change and it should be mentioned in docs as well.

**Comment by xon52** [comment]
Yeah I will do.
Are you sure it's breaking? Vue automatically converts camel to kebab. Didn't break on anything I am using it on?

**Comment by thebrownfox** [comment]
@xon52  Didn't work in my case. I changed the docs but I surely missed some events.

**Comment by thebrownfox** [comment]
I guess it works when event is in camelCase and you listen for kebab-case. It doesn't work vice versa.

**Comment by thebrownfox** [comment]
Shouldn't work that way either according to vue documentation https://vuejs.org/v2/guide/components-custom-events.html#Event-Names

**Comment by xon52** [comment]
@thefoxie I just deployed v0.3.27 with support for both camel and kebab. Didn't realise it was a breaking change so I will remove camel in the next major 😅
