### ISSUE TITLE
Feature requrest : Mark Clustering

### ISSUE THREAD

**Issue by tingan** [xon52/x5-gmaps#17]
I find the x5-gmaps now does have all the functions i need except the mark clustering (https://developers.google.com/maps/documentation/javascript/marker-clustering), as the markers number is getting bigger and unmanageable soon. thanks.

**Comment by DCSnip3r** [comment]
I agree this is a good feature

**Comment by xon52** [comment]
This will be the next change after the upgrade of Typescript and Vue 3 support.

**Comment by xon52** [comment]
I've broken my docs build and am waiting for some help to fix them, but I have made this component.
Still needs to be tested and refined, but the basic function is there.

Check it out by selecting Marker Cluster from the dropdown here: [Demo](https://codesandbox.io/s/x5-gmaps-demo-6xww1?file=/src/examples/MarkerCluster.vue)
And have a look at what the docs will eventually say about them here: [Cluster docs](https://github.com/xon52/x5-gmaps/blob/master/docs/api/cluster.md)
