### ISSUE TITLE
Drop pin - Click on Map

### ISSUE THREAD

**Issue by walnut-co** [xon52/x5-gmaps#18]
is there a way to drop a marker on the map, when user click somewhere on the map.
please see below

![ezgif com-gif-maker](https://user-images.githubusercontent.com/13636878/98442606-41816a00-2151-11eb-9993-ec7a812f98a9.gif)

Thanks

**Comment by xon52** [comment]
Yes. First thing is to have an array of markers for all your markers on the map, and then use `v-for` to put a `<gmaps-marker>` inside the `<gmaps-map>` component for each of those.
Secondly, you can listen to the `@click` event of the `<gmaps-map>` component which returns an event that includes a [Google Maps LatLng object](https://developers.google.com/maps/documentation/javascript/reference/coordinates) of where has been clicked. From that, you can add a new marker to your marker array and it should update with a new marker.

But had some time so made you an example. Go have a look here: [https://xon52.github.io/x5-gmaps/](https://xon52.github.io/x5-gmaps/) and select the "Drop a Marker" link.
