### ISSUE TITLE
Marker icon - only string

### ISSUE THREAD

**Issue by thebrownfox** [xon52/x5-gmaps#19]
Marker icon should be either string or object (define different size).

**Comment by xon52** [comment]
Hey @thefoxie can you elaborate a bit?

**Comment by thebrownfox** [comment]
Hey @xon52 I meant the options like label or icon are expected to be strings instead of strings or objects with options. I used the options prop but I'm not sure if there isn't issues with reactivity you mentioned in the docs. Sometimes the markers won't change which is weird but they shouldn't even work then (the url for the icon is in the object as well). Maybe it's related to gmaps library itself. Take a look. 
![image](https://user-images.githubusercontent.com/15309350/98795006-0198dc00-240a-11eb-991c-9ed60a7567c3.png)
![image](https://user-images.githubusercontent.com/15309350/98795121-2725e580-240a-11eb-9915-5a407573d1a1.png)

**Comment by xon52** [comment]
This is really odd. I actually guessed this would happen while I was writing it but never observed it.
With the marker you can give it a label or icon prop (which has to be a string) or set them in the options object.
The options object gets put straight into the Google Maps API, so if you don't get errors, Google API accepted it.

Having said all that, it's Vue we're talking about, and I'm also no expert plugin builder, so it could very well be an issue on my/Vue's side which I'd like to test. Any chance you can replicate it?

**Comment by thebrownfox** [comment]
I don't see problem in the marker component as it gets recomputed but those markers are changed 1) right after load (short flick) 2) Or stay big and all change just after I click on marker. I pass following object to prop options:
``` json
{
    "label":{
        "text":"8",
        "fontSize":"14",
        "fontFamily":"",
        "color":"",
        "fontWeight":""
    },
    "icon":{
        "url":"/assets/img/marker_icon_green.b1bc36f0.png",
        "size":{
            "width":48,
            "height":48,
            "j":"__vue_devtool_undefined__",
            "i":"__vue_devtool_undefined__"
        },
        "scaledSize":{
            "width":48,
            "height":48,
            "j":"__vue_devtool_undefined__",
            "i":"__vue_devtool_undefined__"
        },
        "anchor":{
            "x":24,
            "y":0
        },
        "labelOrigin":{
            "x":24,
            "y":18.390804597701152
        }
    }
}
``` 
It's strange it takes url but not the other properties which might be because if maps library is not loaded I don't set those other properties. Real solution to this would be to generate those options (you gotta provide gmaps objects like  new Maps.Size()) in marker component

**Comment by thebrownfox** [comment]
```vue
<gmaps-marker
    v-for="(marker, markerIndex) in markers"
    :key="'marker-' + markerIndex"
    :position="marker.position"
    :options="
        getMarkerOptions({
            labelText: marker.location.devices_count,
            iconURL: marker.icon,
        })
    "
    @click="showMarker(marker)"
/>
<script>
export default {
    methods: {
        getIcon(iconURL) {
            let icon = {
                url: iconURL,
            };
            if (Maps) {
                icon.size = new Maps.Size(markerSize, markerSize);
                icon.scaledSize = new Maps.Size(markerSize, markerSize);
                icon.anchor = new Maps.Point(markerSize / 2, 0);
                icon.labelOrigin = new Maps.Point(
                    markerSize / 2,
                    markerLabelPosition
                );
            }
            return icon;
        },
        getLabel(labelText) {
            let label = {
                text: labelText.toString(),
            };
            if (Maps) {
                label.fontSize = markerFontSize.toString();
                label.fontFamily = "";
                label.color = "";
                label.fontWeight = "";
            }
            return label;
        },
        getMarkerOptions(markerOptions) {
            const options = {
                label: this.getLabel(markerOptions.labelText),
                icon: this.getIcon(markerOptions.iconURL),
            };
            return options;
        },
    },
};
</script>
```

**Comment by xon52** [comment]
@thefoxie I have tried to replicate this and can't. I didn't try with the label as the label seems to be scaling fine from your pictures, but when I use an object for icon properties in the options object mine seems to work.

I added a new feature to the [example page](https://xon52.github.io/x5-gmaps/) to help me to test things like this, but you can see my test if you hold Ctrl and click on the blue logo.

This is how those are generated:

```html
<gmaps-marker v-for="(marker, markerIndex) in items" :key="'marker-' + markerIndex" :options="marker" />
```

```js
created() {
    this.$GMaps().then((GMaps) => {
      const markerSize = 30

      for (let i = 0; i < 5; i++)
        this.items.push({
          position: {
            lat: -27.5 + Math.random() / 10 - 0.05,
            lng: 153 + Math.random() / 10 - 0.05
          },
          icon: {
            url: 'https://cdn0.iconfinder.com/data/icons/entypo/89/small18-128.png',
            size: new GMaps.Size(markerSize, markerSize),
            scaledSize: new GMaps.Size(markerSize, markerSize),
            anchor: new GMaps.Point(markerSize / 2, 0)
          }
        })
    })
  }
```

Happy to test it more if you can help me replicate it.

**Comment by thebrownfox** [comment]
@xon52 I bet it would be because of the way I work with the GMaps library. It works internally as computed of marker component changes but the DOM elements of GMaps don't reflect it. I will test it out tomorrow and maybe we could add note to the docs about right usage. 

But originally this issue was about the named props like `:icon` or `:label` accepting strings only. The init of those options could be even done internally inside marker and thus we wouldn't need to call it on created() with ` this.$GMaps().then((GMaps) => {})` which could make it easier to work with. Same as `:position` prop that accepts object just with extra steps.

**Comment by xon52** [comment]
I understand. I have made that change so that the inline icon and label properties can now accept objects.
If the issue persists, please make a new issue with a reproduction.
