### ISSUE TITLE
Support for Polylines?

### ISSUE THREAD

**Issue by daviddesmet** [xon52/x5-gmaps#2]
First of all, thank you for creating this amazing plugin for Vue.

I would like to ask if you have any plans to add support for drawing polylines on the map. A use case will be for drawing the path a certain marker took (from a start position to end position), for example in JavaScript:

```javascript
// This example creates a 2-pixel-wide red polyline showing the path of
// the first trans-Pacific flight between Oakland, CA, and Brisbane,
// Australia which was made by Charles Kingsford Smith.

function initMap() {
var map = new google.maps.Map(document.getElementById('map'), {
  zoom: 3,
  center: {lat: 0, lng: -180},
  mapTypeId: 'terrain'
});

var flightPlanCoordinates = [
  {lat: 37.772, lng: -122.214},
  {lat: 21.291, lng: -157.821},
  {lat: -18.142, lng: 178.431},
  {lat: -27.467, lng: 153.027}
];
var flightPath = new google.maps.Polyline({
  path: flightPlanCoordinates,
  geodesic: true,
  strokeColor: '#FF0000',
  strokeOpacity: 1.0,
  strokeWeight: 2
});

flightPath.setMap(map);
}
```

Which renders:

![image](https://user-images.githubusercontent.com/2607383/84800952-2bb5b180-afc4-11ea-9ed8-d576e196eb3b.png)

Would be nice to be able to support multiple polylines with options to set the color, opacity, line weight, etc.

Edit: Ref https://developers.google.com/maps/documentation/javascript/examples/polyline-simple

Hope you can consider.
Thanks in advance!

**Comment by xon52** [comment]
Hey mate, thanks for trying it out. Absolutely, it's just been a time issue for me.
For my projects I don't need it so it hasn't been a priority (which I can also use work time for); but it's been constantly on my todo list so now that you've asked, maybe this weekend!

**Comment by daviddesmet** [comment]
Thanks a lot for considering the feature, I’m looking forward to it 😊

**Comment by JoKre17** [comment]
Hey everyone,

since you started an issue regarding a new feature which basicly is to be able to add basic GMaps elements, I wanted to share how I did a short workaround, as long as this is not supported by @xon52 . :D


Hint: $refs.gmap is the component from x5-gmaps.

`
// adding the search circle when map is ready
_eventSearchComponent.$refs.gmap.getAPI().then((GMaps) => {

    var circle_options = {
        strokeColor: "#FF0000",
        strokeOpacity: 0.8,
        strokeWeight: 2,
        fillColor: "#FF0000",
        fillOpacity: 0.35,
        center: _eventSearchComponent.search.position, // use the already set search position
        /**
         * radius is input in metres and taken from the props,
         *
        radius: _eventSearchComponent.searchRadius * 1000,
        draggable: false, // only the marker is draggable and the circle will be updated
    };
    _eventSearchComponent.search.circle = new GMaps.Circle({
        map: _eventSearchComponent.$refs.gmap.getMap(),
        ...circle_options,
    });

    // what I actually didn't get to work...   :/
    //circle.bindTo('center', _googleMapLoader.$refs.searchPosition, 'position');
});
`

![grafik](https://user-images.githubusercontent.com/16329454/84933062-99053780-b0d5-11ea-86e3-fc98b4cf87f3.png)

I'm looking forward to maybe see a more generic solution to this issue! 👍 
And thanks for being open to develop this further. :)

**Comment by xon52** [comment]
OK v0.3.11 is up and includes polylines. [Here's an example](https://xon52.github.io/x5-gmaps/#polylinesandpolygons).

Any problems, just make a new issue.

Circles and rectangles should be very similar so I'll do that tomorrow 😇

**Comment by xon52** [comment]
@idaviddesmet @JoKre17 v0.3.12 now also have rectangles and circles FYI.
[Here's the example](https://xon52.github.io/x5-gmaps/#rectanglesandcircles)

**Comment by daviddesmet** [comment]
Thanks @JoKre17 for the tip, This week was hectic at work and didn't get time to look back at this.
Wow! Thanks a lot @xon52 for being so quick on implementing polylines and also for the step further by adding circles and rectangles 😊
