### ISSUE TITLE
infoWindo issue

### ISSUE THREAD

**Issue by abbeMoh** [xon52/x5-gmaps#22]
( Error in callback for watcher "options": "TypeError: Cannot read property 'setOptions' of undefined"
Cannot read property 'setOptions' of undefined ) 

Code =
 <gmaps-info-window v-if="canOpenInfoWindo" @closed="hideInfoWindow()"
:options="{position:{lat:infoLat, lng:infoLng},content:info,minWidth:250,pixelOffset:{width:0,height:-38}}" :key="infoLat+infoLng"/>

**Comment by xon52** [comment]
Fixed in v0.3.29.
Thanks for pointing it out @abbeMoh 👍
