### ISSUE TITLE
Support for vue3

### ISSUE THREAD

**Issue by thebrownfox** [xon52/x5-gmaps#25]
Pretty self explanatory. I'll provide the PR. Do you want to split it to another repo, create monorepo or have branches like main containing vue3 code and vue2 branch containing vue2 code? Or main could have vue2 and next vue3 till the shift in npm vue package when vue will become vue3 by default.

**Comment by xon52** [comment]
Great question. I have been wanting to do this but decided to wait until it's released.
I am able to be swayed, but how about a monorepo for now?
I would like to make some bigger changes too and seeing as Vue3 may have some breaking changes it makes sense to include all of those together in v1.0.

Having said that, when compiled it shouldn't make any difference, so Vue3's more for dev than anything.

**Comment by stereonom** [comment]
Hi.
Any plans or dev-branches for vue3-support?

I'd love to use it in a project as all the other gmap plugins seems crappy.

**Comment by xon52** [comment]
@thefoxie may have gotten side tracked. I'll find some time this weekend to scope it out. Been meaning to anyway. Thanks for the prompt @stereonom

**Comment by xon52** [comment]
As an update, I have started work on this. I will publish a beta soon (~1 week) for comments and changes from anyone interested.
As it's long overdue (and already requires a total rewrite), it will be a major update to v1.0 and be written in Typescript.

**Comment by thebrownfox** [comment]
@xon52 I wish I had the time. I've got 2 projects simultaneously and it's nuts (no time for anything). I will be glad if I'm able to help with something/anything, just mention me.

**Comment by xon52** [comment]
All good @thefoxie, when I'm done I'll ping you for a code review and test.

**Comment by kbottner** [comment]
I was giving x5-gmaps a try using Vue3 when it appears I ran into a related issue.

Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Module.eval (index.js:21)
    at i (index.js:1)
    at eval (index.js:1)
    at eval (index.js:1)
    at eval (index.js:1)
    at eval (index.js:1)
    **at Object../node_modules/x5-gmaps/dist/index.js (chunk-vendors.js:1934)**
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/components/Gmap.vue?vue&type=script&lang=js:6)

I haven't been able to work around it so wondering if this is part of the Vue3 issue?

(Oh and this was just using the simple example in the readme.)

**Comment by xon52** [comment]
@kbottner I just fixed a breaking issue but I think it's different to what you're describing. I will see if I can do a quick and dirty Vue3 port ASAP. I ran into some technical challenges in my first Vue 3 version and decided to fix up Vue 2 version first.

**Comment by kbottner** [comment]
Happy to give it a try when you have something ready.

**Comment by markpruett571** [comment]
Hi, @xon52. Is this Vue3 version published on npm?

**Comment by xon52** [comment]
@markpruett571 TBH this just fell behind and I was too busy to restart it. Might try pick it up again this weekend.

**Comment by xon52** [comment]
I know it's late and people have probably moved on with their lived, but I have finally finished the new (fully typed) Vue 3 version: [v3-gmaps](https://github.com/xon52/v3-gmaps). Docs on the way but demo is [here](https://vue-bujcvu.stackblitz.io).
Really keen to get some testers and feedback.
