### ISSUE TITLE
move event not firing in nuxt application

### ISSUE THREAD

**Issue by phani1kumar** [xon52/x5-gmaps#28]
I am new to both vue and nuxt. It took quiet a bit of time to figure out how to make this plugin work in Nuxt. I am using Nuxt js 2.14. 

I've had to create a plugin and mark it as `{ src: '~/plugins/x5-maps.js', ssr: false }` to make the plugin work. After all the setup, and trying to capture the "move" event for the marker, the even is never firing. 
```
  <template>
  <div id="app">
    <gmaps-map @mounted="ready">
      <gmaps-marker :position="markerPos" :options="markerOptions" @positionChanged="updatePosition" />
    </gmaps-map>
    <input id="autocomplete" ref="autocomplete" placeholder="Search">
  </div>
</template>
<script>
import { gmapsMap, gmapsMarker } from 'x5-gmaps'
export default {
  components: { gmapsMap, gmapsMarker },
  data: () => ({
    autocomplete: null,
    places: null,
    map: null,
    marker: null,
    markerPos: { lat: -27, lng: 153 },
    markerOptions: {
      draggable: true,
      clickable: true
    }
  }),
  methods: {
    ready (map) {
      this.map = map
      this.$GMaps().then((maps) => {
        this.places = new maps.places.PlacesService(map)
        this.autocomplete = new maps.places.Autocomplete(this.$refs.autocomplete)
        this.autocomplete.addListener('place_changed', this.update)
      })
    },
    updatePosition (pos) {
      console.log('Position changed to:', pos)
      this.markerPos = pos
    },
    addMarker ($event) {
      // Stop last marker from bouncing
      if (this.markers.length) { this.markers[this.markers.length - 1].animation = null }
      // Add new marker with a bounce
      this.pos = pos.head
      const position = $event.latLng.toJSON()
      this.markers.push({ position, animation: this.bounce })
    },
    update () {
      const place = this.autocomplete.getPlace()
      if (place.geometry) {
        this.map.panTo(place.geometry.location)
        this.markerPos = place.geometry.location
      }
    }
  }
}
</script>
<style lang="css" scoped>
/* ... */
#app {
  height: 100%;
  width: 100%;
}
* >>> #autocomplete {
  border: 3px solid rgba(0, 60, 255, 0.329);
  font-size: 18px;
  height: 40px;
  left: 40%;
  padding: 0 10px;
  position: absolute;
  top: 0;
  width: 20%;
  z-index: 1;
}
</style>
```
Here, the mounted event of the `gmaps-map` is firing properly, but the "move" event of `gmaps-marker` is not firing.
Please help me understand if I've to do anything specific to use this component library in NUXT JS

**Comment by xon52** [comment]
Hi @phani1kumar, I'm not an expert in Nuxt myself and have not tested this using Nuxt - but I think it should be fine in theory.

Looking at your code I see you have `@positionChanged` which has been depreciated (and may now be broken), but you mention `@move` in your description - so first, can you confirm you're using `@move` and not `@positionChanged`?

**Comment by phani1kumar** [comment]
Thank you @xon52  for your reply. Thank you very much for such a beautiful library, you made my life simple with the library and the nice examples. I've tried `move` first and then changed to `positionChanged` and `position_changed` just to test if the original event is firing up. I was able to manage to solve the problem by registering a listener to `position_changed` during `@mouseover` and was able to get my application working. 

```      
<gmaps-marker id="imageMarker" ref="imageMarker" :position="markerPos" :options="markerOptions" @mouseover="updatePosition" />

....
....
    updatePosition () {
      this.$GMaps()
        .then((GMaps) => {
          this.marker = this.$refs.imageMarker.marker
          if (!this.markerMoveRegistered) {
            this.markerMoveRegistered = true
            this.marker.addListener('position_changed', () => {
              const position = this.marker.position.toJSON()
              // console.log('Position::', position)
              if (position) {
                this.markerNewPos = position
              }
            })
          }
        })
      // this.markerPos = pos
    },

```

Not sure if this is correct, but it is working. `position_changed` is the event raised by Google library, so that is not deprecated and shall work normally.

**Comment by xon52** [comment]
By depreciated I mean I don't plan on forwarding the Google Maps event `position_changed` to my Vue package event `positionChanged` in the future. What you did was clever but a bit of a hack by accessing the Google Maps events through the Vue component - I'm still confused as to why you have needed to do that.

What about the other events from the component? e.g. `@click`, `@mouseover'

If you use Vue Devtools (Nuxt may need an extra setting or two), can you check out the events firing?

**Comment by phani1kumar** [comment]
`@click, @mouseover` they did trigger. Also in the gmapsMap the `@ready` event also fired, I couldn't understand the reason why the `@move` didn't fire in gmapsMarker, that sounded weird. 

But as I told earlier, I am  no expert in Vue or Nuxt. Still a learner, hence couldn't really figure out what is going wrong in this particular case!

**Comment by xon52** [comment]
OK, well if you see it again or find out why, please let me know.

**Comment by phani1kumar** [comment]
sure, I'll. Thank you for such a nice library and the support.

**Comment by clonixdev** [comment]
> Gracias @ xon52 por su respuesta. Muchas gracias por una biblioteca tan hermosa, me simplificaste la vida con la biblioteca y los buenos ejemplos. Lo intenté `move`primero y luego cambié `positionChanged`y `position_changed`solo para probar si el evento original se está activando. Pude resolver el problema registrando un oyente `position_changed`durante `@mouseover`y pude hacer que mi aplicación funcionara.
> 
> ```
> <gmaps-marker id="imageMarker" ref="imageMarker" :position="markerPos" :options="markerOptions" @mouseover="updatePosition" />
> 
> ....
> ....
>     updatePosition () {
>       this.$GMaps()
>         .then((GMaps) => {
>           this.marker = this.$refs.imageMarker.marker
>           if (!this.markerMoveRegistered) {
>             this.markerMoveRegistered = true
>             this.marker.addListener('position_changed', () => {
>               const position = this.marker.position.toJSON()
>               // console.log('Position::', position)
>               if (position) {
>                 this.markerNewPos = position
>               }
>             })
>           }
>         })
>       // this.markerPos = pos
>     },
> ```
> 
> No estoy seguro de si esto es correcto, pero está funcionando. `position_changed`es el evento generado por la biblioteca de Google, por lo que no está obsoleto y funcionará normalmente.

I was experiencing the same incident with the @move event, this solution worked for me in v0.5.9
