### ISSUE TITLE
 Access Google map instance ?

### ISSUE THREAD

**Issue by sam0910** [xon52/x5-gmaps#30]
Greetings!
Thank you for your great map component. 
I've read 'README' and the issues with 'thefoxie' ,
but I am poor at Vue, I could not access the google map instance.

Could you help me to understand how to use it ?
I'd like to use Google map methods(ex:panTo) after it's mounted with some click function.
I've tried this,
```<script>
import { gmapsMap, gmapsMarker, gmaps } from "x5-gmaps";
export default {
   components: { gmapsMap, gmapsMarker },
   data: () => ({
      mapInstance: null,
   methods: {
      someClickFuntion() {
      this.mapInstance.panTo({lat:0,lng:0});
    },

mounted() {
    gmaps().then((GMaps) => {
      this.mapInstance= GMaps;
    });
  },
```
Error :TypeError: this.mapInstance.panTo is not a function

**Comment by xon52** [comment]
Sorry for taking a while to reply, I have been busy with Christmas.
You have misunderstood what `gmaps()` does - it returns the Google Maps API (which is what is used to create Google Maps objects).
You want the instance created which is primarily accessible through the `<gmaps-map>` component which emits a reference to itself using the `mounted` event:

```js
<gmaps-map @mounted="setMapInstance" />
// ...
methods: {
  setMapInstance(map) {
    this.mapInstance = map
  },
  someClickFunction() {
    this.mapInstance.panTo({lat:0,lng:0});
  }
}
```

I hope that makes sense and works as I'm away from my computer to test; but ask if you have any more questions.

**Comment by sam0910** [comment]
Thank you for the present.
It works so well. :)

Merry Christmas ,
