### ISSUE TITLE
[Feature Request] GeoJSON features component

### ISSUE THREAD

**Issue by thebrownfox** [xon52/x5-gmaps#32]
It should be possible to create component with geojson instead of google objects. I do create polygons like this as I receive large (sometimes 70k points) sets of data that I work with and it would be preferred to not process the data just for component again . I've added this to my app, but not as a component. I will look into this later and send PR.

**Comment by xon52** [comment]
I've added support for this. I'm sure it can be improved, but I need someone to try it out and provide feedback.

As always, open a new ticket when you have a suggestion or if there are any issues related to this new feature.
