### ISSUE TITLE
failed init for V3 version

### ISSUE THREAD

**Issue by gerritvanaaken** [xon52/x5-gmaps#35]
Hi, I wanted to give V3 alpha a trial and installed it via `npm install x5-gmaps`, the resulting package.json entry looks good: `"x5-gmaps": "^1.0.0-alpha.3"`

My main.js looks like this:

``````
import {createApp} from 'vue';
import App from './App.vue';
import router from './router';
import store from './store';
import gmaps from 'x5-gmaps';

const app = createApp(App);

app
	.use(router)
	.use(store)
	.use(gmaps, {
		key: 'xXXxxxxXXXXxXXXXXXX'
	})
	.mount('#app');
``````

And I’m getting serious error messages in the console, my app wouldn’t start anymore. Here is what I get from Chrome Dev Tools:

``````
index.js?a960:1 Uncaught TypeError: Cannot set property '$GMaps' of undefined
    at e.default (index.js?a960:1)
    at Object.use (runtime-core.esm-bundler.js?5c40:2949)
    at eval (main.js?56d7:14)
    at Module../src/main.js (app.js:2254)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Object.1 (app.js:2315)
    at __webpack_require__ (app.js:849)
    at checkDeferredModules (app.js:46)
    at app.js:925

e.default @ index.js?a960:1
use @ runtime-core.esm-bundler.js?5c40:2949
eval @ main.js?56d7:14
./src/main.js @ app.js:2254
__webpack_require__ @ app.js:849
fn @ app.js:151
1 @ app.js:2315
__webpack_require__ @ app.js:849
checkDeferredModules @ app.js:46
(anonymous) @ app.js:925
(anonymous) @ app.js:928
``````

I have no idea how to debug this, any help is much appreciated!

**Comment by xon52** [comment]
Hey @gerritvanaaken, I am actively developing this in all the free time I have. Was meant to be finished this week but will be another week at least after testing etc.
Some tricky challenges with upgrading it to support Vue 3, composition API, and Typescript. I'll keep you posted, but it won't be long.

**Comment by gerritvanaaken** [comment]
No pressure, just a first feedback which might be useful for your further work on the plugin!

**Comment by xon52** [comment]
The problem here is the library is written in and for Vue 2. Now that we have Typescript support I will be able to focus on Vue 3 as the next major rework. It's coming!!
Also Vue 3 support is already raised as an issue here: #25
