### ISSUE TITLE
Drop and move marker

### ISSUE THREAD

**Issue by kossa** [xon52/x5-gmaps#38]
Hello,

There is a way to move/marker and get the lat/lng ?

Thanks

**Comment by xon52** [comment]
I recommend having a look at the [marker options example](https://github.com/xon52/x5-gmaps/blob/master/example/examples/MarkerOptions.vue). You will notice that the `@move` event emits the position for you to use.

The update for this I'm working on now will change the event name to be more consistent with the Google Maps docs, but for now I think you want `@move`.

**Comment by kossa** [comment]
Alright what I need thanks :)

**Comment by kossa** [comment]
The move event does not fired on my code, also in [marker options example](https://github.com/xon52/x5-gmaps/blob/master/example/examples/MarkerOptions.vue) 

check the [demo](https://xon52.github.io/x5-gmaps/)

![image](https://user-images.githubusercontent.com/1175584/111426783-77cd8800-86f5-11eb-90d2-5e8bdfcd1c9c.png)

**Comment by xon52** [comment]
Thanks for finding this. Problem solved. Surprised it hasn't been complained about before 🤔
Check it's working on your side @kossa and then close this if it's good.
The next version will have much better support in this area.

**Comment by kossa** [comment]
I confirm it works fine

![image](https://user-images.githubusercontent.com/1175584/111438424-83747b00-8704-11eb-8fa1-908bc5bc6c14.png)
