### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by MartCube** [xon52/x5-gmaps#4]
This may not be directly relevant to this repo, But I'm using your maps and they are really nice. 
However I noticed when they load they have a grey background and a white circle spinner. 
Is there anyway to customize this ?

**Comment by xon52** [comment]
That's an interesting question. It is currently just a static div that uses the class gmaps-spinner which is not customisable, but I don't see why it can't be using a slot. I can add that in.
I am curious though, it really should not be visible for very long. It's visible while the the map is loaded plus 100ms, but I never see it for more than a flash. Is there a noticeable delay or is it just a little thing you noticed?
Also to clarify, you're wanting to change the background colour too?

**Comment by MartCube** [comment]
I noticed it when i worked on loading indicator for my app. It is not something really noticeable , it is a small time as you said. 
However for cleaner app design I would love to be able to customize it or at least to be able to remove the circle and have just a background color.

**Comment by xon52** [comment]
OK @MartCube should be possible now with v0.3.13

Check out the docs [here](https://github.com/xon52/x5-gmaps#custom-map-slots). Have a play around and let me know if there are any issues with the solution.
