### ISSUE TITLE
Question ( non issue ). How to apply fitBounds to the map instance. 

### ISSUE THREAD

**Issue by roryheaney** [xon52/x5-gmaps#43]
I'm able to access the map instance, but I feel like I'm doing something else wrong ( markers load correctly, popup window works great ect ):

Mounted:

    this.$GMaps().then((GMaps) => {
			
			this.mapInstance = GMaps;

		}).then(() => {

			this.getLocationService();

		});

And when I reference it again for my API call, I get **fitbounds is not a function:**

    Service.getLocations(this.formData).then((response) => {

		const results = response.data;
		// eslint-disable-next-line no-undef
		this.bounds = new google.maps.LatLngBounds();

		this.markers = results;

		results.forEach((data) => {
			const marker = data.position;
			// eslint-disable-next-line no-undef
			const position = new google.maps.LatLng(marker);
			this.bounds.extend(position);
		});

	})
          .then(() => {
	          const map = this.mapInstance;
	          console.log(map);
	          map.fitBounds(this.bounds);
          })
          .catch((error) => {
          // eslint-disable-next-line no-console
	          console.log(error);
          });

I feel like I'm missing something, or should `fitBounds` be applied different in this plugin?

**Comment by xon52** [comment]
Hi @roryheaney I'm happy to clarify - and acknowledge maybe there needs to be better docs on this.
`this.$GMaps()` returns the Google Maps API - not the map instance.
To get the map instance you need to add `@mounted` on your map component and it will return the instance after it is created and rendered:
```html
<gmaps-map @mounted="test" />
```
```js
// ...
methods: {
  test(map) {
    this.mapInstance = map
  }
},
// ...
```

Happy to explain more if you need, but the steps taken to render the final map are:
```
1. Load Vue
2. Load Google Maps API (which is what $GMaps() returns)
3. Create and mount the x5-gmaps map component (with an empty div)
4. Use Google Maps API to replace the empty div with its Map
5. Emit the reference to the Google Maps API created Map (what @mounted returns)
```

**Comment by roryheaney** [comment]
@xon52 OOOO, gotcha.  Yeah that makes total sense now.  

That also did it for me. Thanks again for the assist, and this plugin really is awesome.  It's been a super easy to use, and the popup option has been great.
