### ISSUE TITLE
vue-property-decorator dependency

### ISSUE THREAD

**Issue by thebrownfox** [xon52/x5-gmaps#57]
It's not mentioned in docs but the project where it's used won't build without it. I no longer use components but I keep the library to load google libs for me which is valid use case I guess(?). I use leaflet now with google maps tiling and autocomplete.

Apart from that, I had lots of fun with this plugin but there's no official support for spiderify in google's map clusterer which is real shame as it's something I have to use ( around 1000 markers and some of them got same lng/lat).

`"x5-gmaps": "0.4.5"` has no problem with the dependency.

**Comment by xon52** [comment]
Hey mate, I'm sorry I missed this. New job floods my notifications and thought I was able to keep an eye out but obviously not.

That's a very interesting implementation, would love to have a look if you don't mind? xon52#5557 on Discord?

Maybe I could add the spiderifying. Will have to read up on it.

Switching over to TS support I needed to use the decorator but I really don't like it. It's currently a peerDependency but they do not work properly in NPM 6 (they were re-instated in NPM 7). Will update now as a dependency and see if that work.s
