### ISSUE TITLE
Alter the mapcenter after it's initialization

### ISSUE THREAD

**Issue by bob606** [xon52/x5-gmaps#59]
Hello, thanks for all of your work on the libary. It's great to use. 

I wanted to ask if there is a way to alter the map center, after it's initialization. As the gmaps options are currently only avaible through an object, you can't change values on the fly through named props like you can do with gmarkers. Is there a workaround for that?

**Comment by pet1330** [comment]
There is a mounted hook which returns the gmap object:

```html
<gmaps-map :options="mapOptions" @mounted="mapReady"></gmaps-map>
```

```javascript
data() {
    map: null
},
methods: {
    mapReady (map) {
      this.map = map
    },
    setCenter(pos) {
        this.map.setCenter(pos)
    }
}

```

then you can either do:

```javascript
this.setCenter(pos)  /* or */  this.map.setCenter(pos)
```
