### ISSUE TITLE
Autocomplete Component Feature Request

### ISSUE THREAD

**Issue by andrehsmendes** [xon52/x5-gmaps#6]
Great plugin.

Would be nice to have the Address auto complete as well as the map.

great work. regards.

**Comment by xon52** [comment]
Out of the immediate scope of this, but I'll leave it here to remind me to have a play around with it.
You can add the relevant library when you `Vue.use()` the plugin in your `main.js` so that you can use it on your own, but I'll see if I can make it a neat shortcut without adding too many bytes 😉

**Comment by stuartpaulin** [comment]
Hi, I see you have made written some commentary about using places / the autocomplete service.  But I'm such a noob that I can't figure out how to actually use query after hours of googling and mucking about.  The best I found is bodging GooglePlacesAutocompletePlugin which is a library that can use the existing open api without double loading the google API.  Though this isn't ideal.  I would super appreciate if you fill out the basic usage of your query function against an inputbox.  Thx so much for a great / clean plugin!

**Comment by xon52** [comment]
@andrehsmendes @stuartpaulin 
Just letting you know that I made a short tutorial on including autocomplete: [Address Autocomplete Example](https://xon5.medium.com/vue-google-maps-and-autocomplete-e9bf0fa3c42e). It's not a component, but should let everyone use autocomplete for now before I find time to get back to component making.

**Comment by andrehsmendes** [comment]
Great, thx for the update on that.

**Comment by xon52** [comment]
Closing this as it remains out of the scope but the example mentioned should help anyone stuck on implementing this.
