### ISSUE TITLE
How can draw in map

### ISSUE THREAD

**Issue by mstfkhazaal** [xon52/x5-gmaps#69]
I have a map and I have to draw it, to demarcate the borders of each piece of land separately.
How do I do this with this library

Like this image 
![1_vr4Cqg_FRtG50D9nZch14Q](https://user-images.githubusercontent.com/47450090/121903856-62d2b600-cd31-11eb-8c28-c1253f6bccca.png)

**Comment by xon52** [comment]
Hi @mstfkhazaal,
There are two ways: [Polylines](https://xon52.github.io/x5-gmaps/api/polylines.html) and [GeoJSON](https://xon52.github.io/x5-gmaps/api/data.html)
Polylines is simple, but overly verbose for tonnes of data points like you'd need there. GeoJSON is much more suited but you will need to use the [GeoJSON](https://en.wikipedia.org/wiki/GeoJSON) data structure. You may have to find the outlines you want already in that format for obvious reasons!

**Comment by mstfkhazaal** [comment]
Thank You but How Can Draw the geojson?

**Comment by xon52** [comment]
That is not in the scope of this project. But Google is your friend.
First result looks pretty good: [https://geojson.io/](https://geojson.io/#map=2/20.0/0.0)
