### ISSUE TITLE
HeatMap Heat - error - 'HeatmapLayer' of undefined

### ISSUE THREAD

**Issue by edwingromero** [xon52/x5-gmaps#7]
Excuse my English.

I am trying to create a HeatMap. I follow the steps in the example but I get an error.

Error: Cannot read property 'HeatmapLayer' of undefined
<img width="623" alt="error gmaps laravel" src="https://user-images.githubusercontent.com/4934593/89004056-f4c30300-d2c6-11ea-88d4-c38c0485bcab.png">

This is the error message that appears

<img width="416" alt="error gmaps" src="https://user-images.githubusercontent.com/4934593/89004074-01dff200-d2c7-11ea-9ff5-d3c5c2d6f710.png">

---------------------------------------
Update 
Silly mistake.
I miss calling the library "visualization"

<img width="524" alt="error gmaps libreria" src="https://user-images.githubusercontent.com/4934593/89004436-ce519780-d2c7-11ea-9193-f544ae71af8c.png">

**Comment by xon52** [comment]
Easy to miss. Glad you found it.
