### ISSUE TITLE
How to remove Google's places from map

### ISSUE THREAD

**Issue by DCSnip3r** [xon52/x5-gmaps#70]
Is it possible to remove the places suggestions that appear on the map as various markers? These can clutter up the information you want to display.

![image](https://user-images.githubusercontent.com/28986986/122130741-b4487700-cdfd-11eb-8f2d-74c30238683b.png)

More generally, is it possible to use a particular map-ID and map-style that you define on Google Maps Platform?

**Comment by xon52** [comment]
So I looked into this a couple of years ago and wasn't successful in finding a way. 
Revisiting this, I have found a potential way (but haven't tested) by [styling a custom map](https://developers.google.com/maps/documentation/javascript/styling) - the `mapId` can be added like so `<map :options="{ mapId: xxx }" />` (it's a standard option property). The limitation is that is not controlled via [my] package and it's a setting in your Google Console.
If you don't want to use Google's style maker you can use this and export the JSON to put into the right place in the Google Console: [Styling Wizard](https://mapstyle.withgoogle.com/)
~~^ The interesting thing about this is it does let you export a Map URL which has the whole custom styling settings as GET params which makes me think there may be a way to do it through the API. Can't find a reference to it though.~~
^ It looks like this JSON can be added to the Styles property of map options: `<map :options="{ styles: xxx }" />`
It takes an array that looks like [this](https://developers.google.com/maps/documentation/javascript/style-reference).

Please let me know if that works or if you find another way that I can maybe turn into a feature, or at least prompt me with method names that I can further investigate.

**Comment by DCSnip3r** [comment]
`:options="{ mapId: xxx }"` works like a charm! Thanks for the reply, this is a perfect solution.

Just need to make sure the mapId you use has your custom style applied. Doing this in the google maps platform is quite easy. In my view, using Google's style maker and applying the style to the map ID is the preferred option over styling the map with the raw array. One advantage of this method is you can chose which map ID to render based on your application environment (eg if you have light/dark mode and want a light/dark mode map)

**Comment by xon52** [comment]
Great! Thanks for sharing. I'll have to have a look at this sometime myself as I suspect that all the `mapId` does is return that JSON you setup via the Google Style Maker. If that's the case then you can shortcut things like darkmode by just changing the JSON in the `styles` prop of `options`.

**Comment by DCSnip3r** [comment]
That's a good idea because updating the style directly would probably be much more performant. Thanks for the suggestion!
