### ISSUE TITLE
Cluster markers

### ISSUE THREAD

**Issue by tomeus** [xon52/x5-gmaps#71]
Hi,

would it be possible to influence map markers through cluster items? I mean, cluster prop items would be an array of marker props. I'm mainly interested in options and icons.

Thanks

**Comment by xon52** [comment]
I'm not following what you'd like to see? You'd like a custom cluster marker?

**Comment by tomeus** [comment]
I'd like custom cluster marker and map marker. 
![Markers](https://user-images.githubusercontent.com/16204382/123398779-31b17b80-d5a4-11eb-9477-093e91591c31.png)
I need to change the map marker image to SVG (Symbol Interface) and easy option to re-style cluster markers (shape, color).

```
<gmaps-cluster
            v-bind:items="mapMarkers" 
            v-bind:options="clusterOptions"
            v-on:click="openPopup"
/>
```
Currently it is possible into mapMarkers pass only lat, lng, id and title (mapMarkers). My suggestion is pass also icon that can be URL, [Icon Interface](https://developers.google.com/maps/documentation/javascript/reference/marker#Icon) and [Symbol Interface](https://developers.google.com/maps/documentation/javascript/reference/marker#Symbol)

Thanks

**Comment by xon52** [comment]
No problem. I wanted to do custom markers for clusters but it's not as simple as individual markers.

You can already do this with markers by the way. Check out the [icon prop for markers in the docs](https://xon52.github.io/x5-gmaps/api/marker.html).

You can see this implemented in the [demo](https://6xww1.csb.app/) if you select `Markers with Options`.

I'll add it to my list and try figure out a neat way to allow custom images for clusters. Do you have an example of how you might want to display it (assuming I can provide the cluster number)?

**Comment by tomeus** [comment]
I know that it is already possible with gmaps-marker component. But when I want to change map marker icon for gmaps-cluster component I'm not able to do it. Unfortunately I need to have custering in my project. Custom cluster markers are not so important as custom map markers for me. So my original suggestion was that gmaps-cluster prop items can accept same parameters as gmaps-marker prop options. Is it possible?

I need to have map marker like this
![Screenshot 2021-06-25 at 13 04 22](https://user-images.githubusercontent.com/16204382/123416446-d76de600-d5b6-11eb-8498-9d812e7ad157.png)
where I can easily change background color (so I want to use Symbol Interface), but even for gmaps-marker component I'm not able to change fillColor. I can create set of icons with different colors and change icon path, but as I mentioned, it is not possible for gmaps-cluster component.

Regarding cluster marker, I need to have it as circle without shadow and be able to set color without percentage change. I was able to achieve it by css overriding.

**Comment by xon52** [comment]
Great. Thanks for that information. As I say, I'll have a look at this some
time soon. It was certainly something I wanted to do at the start but
haven't had the time.

As always, of anyone else wants to have a try I'm keen to have more
contributors!

**Comment by tomeus** [comment]
Hi,

there is PR that I think solves my requirements https://github.com/xon52/x5-gmaps/pull/72

PS: A guide for contributors would be useful :-)

**Comment by xon52** [comment]
Thanks very much for that. Apologies it took so long to look at it. I was making a bunch of other changes and so will finish those before releasing it all together.
And I hear you about the contributors guide. Time is my biggest challenge but I do appreciate that helps other people help which saves me time - so it's worth it!
