### ISSUE TITLE
Extend docs/readme on how to access and use GMaps instance

### ISSUE THREAD

**Issue by thebrownfox** [xon52/x5-gmaps#8]
Hey, I wanted to use places plugin, but had no idea how to use it. It could save some time if it were mentioned in the docs. I will submit a PR if you have no time.

**Comment by xon52** [comment]
Thanks for the prompt. I actually had to play around with this very recently and it wasn't intuitive. I have added a section in the docs for it, but if you have a better way you found, or have something to add, I'm very happy for more PR contributors.
