### ISSUE TITLE
Cluster component does not bind the `options` prop on Marker component

### ISSUE THREAD

**Issue by treystout** [xon52/x5-gmaps#81]
The Marker component looks like it should handle [MarkerOptions](https://developers.google.com/maps/documentation/javascript/reference/marker#MarkerOptions.optimized) however when the markers are created by the Cluster component, [options isn't bound on the Marker](https://github.com/xon52/x5-gmaps/blob/master/src/components/Cluster.vue#L12).

All of this is so I can set `optimized: false` on my clustered pins. Making that a prop on `Marker` would be a bonus, but I don't think is necessary at the moment.

**Comment by xon52** [comment]
Good point. And what horrible code I write.
