### ISSUE TITLE
Modal problem in 

### ISSUE THREAD

**Issue by shamshadpattani** [xon52/x5-gmaps#86]
Google Maps Autocomplete input field inside Bootstrap modal dialog and the autocomplete result is not displayed. However, if I press the down arrow key, it selects the next autocomplete result, so it seems that the autocomplete code works correctly, only that the result is not displayed correctly. Maybe it's hidden behind the modal dialog?

i tried
```
.pac-container {
    z-index: 10000 !important;
}
```
Now I'm struggling to make autocomplete working inside 2nd layer Boostrap Modal. Unfortunately, the z-index trick doesn't work here.

**Comment by xon52** [comment]
Hey, I'm sorry it's taken me a while to respond. I am not following what you mean? You've put a map with autocomplete into a Bootstrap Modal and it's not showing correctly?
Can you make a demonstration on codesandpit.io or something so I can have something to test against?
