### ISSUE TITLE
Editing shape event

### ISSUE THREAD

**Issue by ahmed-aliraqi** [xon52/x5-gmaps#9]
How to update polygon `paths` when editing the shape by dragging the control points?

**Comment by xon52** [comment]
Hmm, I thought I had this working but clearly not. Will get onto it ASAP.

**Comment by xon52** [comment]
@ahmed-aliraqi this is a problem with Google Maps Polygon's events being either poorly designed or poorly documented, but I have made a solution which is available on **v0.3.21**. I have combined the events `remove_at` and `mouseup` for the polygon to emit a `pathChanged` event (only when the line is editable).

Please raise another issue if you find any problems with this solution.

You can see the new event in this example: [https://github.com/xon52/x5-gmaps/blob/master/example/ExamplePolyline.vue](https://github.com/xon52/x5-gmaps/blob/master/example/ExamplePolyline.vue)
