### ISSUE TITLE
How to change Marker origin

### ISSUE THREAD

**Issue by dvdbrk** [xon52/x5-gmaps#97]
I am trying to set the `origin` for marker, but I do not know how to access `maps.Point`. Any ideas?

```
            icon: {
                url: '.../myimage.png',
                scaledSize: new maps.Size(60, 30),
                origin: new maps.Point(30, 30),
            },

```

**Comment by xon52** [comment]
So it's a little tricky and fiddly., but you need to [use the promise which returns the Google Maps API](https://xon52.github.io/x5-gmaps/advanced.html#accessing-the-google-maps-api).

Here's something I added to use it in [this demo file](https://github.com/xon52/x5-gmaps/blob/master/dev/src/examples/MapOptions.vue).
```js
import { gmapsMap, gmapsMarker, gmaps } from 'x5-gmaps';
...
  async mounted() {
    gmaps().then(
      (x) =>
        (this.optionsB.icon = {
          url: 'https://ktcables.com.au/wp-content/uploads/2018/10/KT701.jpg',
          scaledSize: new x.Size(60, 30),
          origin: new x.Point(10, 10)
        })
    );
  },
```

_Edit: I also noticed that if you change your origin to the same numbers as your scale you won't see the image at all as it moves the image outside of the scaled size window._

**Comment by dvdbrk** [comment]
Brilliant, this works, thank you.
