### ISSUE TITLE
Using Marker Cluster with popup

### ISSUE THREAD

**Issue by kossa** [xon52/x5-gmaps#99]
Hello,

I want to use Marker Cluster and when the user click on a marker I want to show a popup with informations

Currently my code like that: 
```
<gmaps-map :options="mapOptions">
      <gmaps-cluster :items="drivers" height="200px"> </gmaps-cluster>
</gmaps-map>
```

and the popup:
```
<gmaps-map :options="mapOptions">
  <gmaps-popup
    v-for="(driver, index) in drivers"
    :key="index"
    :position="driver.position"
    height="200px"
    :background="driver.organ_transfer ? 'red' : '#ddd'"
  >
    <div class="text-center">
      <a
        class="d-block"
        :class="{
          'text-success': !driver.organ_transfer,
          'text-white': driver.organ_transfer,
        }"
        href="#"
        @click.prevent="driver.full_details = true"
        >{{ driver.name }}</a
      >
      <div
        v-if="driver.full_details"
        :class="{
          'text-success': !driver.organ_transfer,
          'text-white': driver.organ_transfer,
        }"
      >
        <img :src="driver.avatar" width="48" class="img-thumbnail rounded-circle" />
        <div>{{ driver.email }}</div>
        <div>{{ driver.phone }}</div>
        <a href="" @click.prevent="driver.full_details = false">Close</a>
      </div>
    </div>
  </gmaps-popup>

</gmaps-map>
```

**Comment by xon52** [comment]
Hmmm, this isn't really possible I'm afraid. It's a good idea which I'd like to put in, but I don't really have time right now.
How it works is when you click on a cluster, it will zoom in to the bounds. When you click on a marker in a cluster, it will emit the `click` event which you can attach a handler to - but you don't get that event from clicking on a cluster.

I might be able to rig something up, but no promises. This is a really old project and I'm pretty busy with other things.

**Comment by kossa** [comment]
I got you, there is an event I can create custom pop-up in the right side,
thank you for the idea 💡

**Comment by xon52** [comment]
I think it will still zoom in when you click on this though. I was going to
see if I could add an optional blocker of that zoom in action.

**Comment by xon52** [comment]
@kossa been a while since I played with this so jumped in and granted your wish in `v0.6.1` 🧙 

The `cluster` component now has a property `zoom-on-click` (defaults to `true`).
If `false`, it won't zoom in, and instead emit the cluster object as a `click` event.

**Comment by kossa** [comment]
Thank you @xon52 I appreciate

**Comment by kossa** [comment]
Sorry to disturb you again, how can I get name when I click on pin

```html
<gmaps-map>
      <gmaps-cluster :items="items" :options="mapOptions" />
</gmaps-map>
```

```js
data() {
    return {
      items: [
        { lat: -27.41, lng: 153.01, name: 'driver1' },
        { lat: -27.42, lng: 153.02, name: 'driver2' },
        { lat: -27.48, lng: 153.08, name: 'driver3' },
        { lat: -27.49, lng: 153.09, name: 'driver4' },
      ],
      center: { lat: 53.4526367, lng: -2.1975704 },
    }
  },
```

Currently here is the click event in the console

![image](https://user-images.githubusercontent.com/1175584/197349814-5923ea48-9de9-4083-b40b-9ce35b18cb87.png)

**Comment by xon52** [comment]
@kossa if it's a new request, please make a new Issue ticket.
If you look at the [cluster demo](https://codesandbox.io/s/x5-gmaps-demo-6xww1?file=/src/examples/MarkerCluster.vue) you can see:
```html
<gmaps-cluster
    :items="items"
    :options="clusterOptions"
    :zoom-on-click="zoomOnClick"
    @click="test"
/>
```

```js
test(e) {
    this.pinClicked = e;
},
```

You need an event handler on the `<gmaps-cluster />` component.

**Comment by kossa** [comment]
I got it the important think is the `id` in the items 
> "id: string which is $emit'd when a pin is clicked."

Thank you again
